AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for GuardDuty findings email notifications'

Parameters:
  EmailAddress:
    Type: String
    Description: Email address to receive GuardDuty notifications

Resources:
  GuardDutyNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: GuardDutyNotificationTopic

  GuardDutyNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref GuardDutyNotificationTopic
      Protocol: email
      Endpoint: !Ref EmailAddress

  GuardDutyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: GuardDutyFindingsRule
      Description: "EventBridge rule to send GuardDuty findings to SNS"
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
      State: ENABLED
      Targets:
        - Arn: !Ref GuardDutyNotificationTopic
          Id: GuardDutyNotificationTarget
          InputTransformer:
            InputPathsMap:
              severity: "$.detail.severity"
              finding_id: "$.detail.id"
              finding_type: "$.detail.type"
              region: "$.region"
              finding_description: "$.detail.description"
            InputTemplate: |
              "You have a severity <severity> GuardDuty finding type <finding_type> in the <region> region. Finding description: <finding_description>. For more details, go to https://console.aws.amazon.com/guardduty/home?region=<region>#/findings?search=id=<finding_id>"

Outputs:
  SNSTopicArn:
    Description: ARN of the SNS topic for GuardDuty notifications
    Value: !Ref GuardDutyNotificationTopic
  EventRuleName:
    Description: Name of the EventBridge rule for GuardDuty findings
    Value: !Ref GuardDutyEventRule